const commonWords = [
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "i",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "is",
  "water",
  "long",
  "find",
  "here",
  "thing",
  "great",
  "man",
  "world",
  "life",
  "still",
  "public",
  "human",
  "read",
  "left",
  "increase",
  "local",
  "sure",
  "something",
  "without",
  "come",
  "me",
  "back",
  "better",
  "general",
  "process",
  "she",
  "heat",
  "thanks",
  "specific",
  "enough",
  "long",
  "lot",
  "hand",
  "popular",
  "small",
  "though",
  "experience",
  "job",
  "book",
  "end",
  "point",
  "type",
  "home",
  "economy",
  "away",
  "big",
  "internet",
  "possible",
  "television",
  "three",
  "understand",
  "various",
  "yourself",
  "card",
  "difficult",
  "including",
  "list",
  "mind",
  "particular",
  "real",
  "science",
  "trade",
  "consider",
  "either",
  "library",
  "likely",
  "nature",
  "fact",
  "line",
  "product",
  "care",
  "group",
  "idea",
  "risk",
  "several",
  "someone",
  "temperature",
  "united",
  "word",
  "fat",
  "force",
  "key",
  "light",
  "simply",
  "today",
  "training",
  "until",
  "major",
  "name",
  "personal",
  "school",
  "top",
  "current",
  "generally",
  "historical",
  "investment",
  "left",
  "national",
  "amount",
  "level",
  "order",
  "practice",
  "research",
  "sense",
  "service",
  "area",
  "cut",
  "hot",
  "instead",
  "least",
  "natural",
  "physical",
  "piece",
  "show",
  "society",
  "try",
  "check",
  "choose",
  "develop",
  "second",
  "useful",
  "web",
  "activity",
  "boss",
  "short",
  "story",
  "call",
  "industry",
  "last",
  "media",
  "mental",
  "move",
  "pay",
  "sport",
  "thing",
  "actually",
  "against",
  "far",
  "fun",
  "house",
  "let",
  "page",
  "remember",
  "term",
  "test",
  "within",
  "along",
  "answer",
  "increase",
  "oven",
  "quite",
  "scared",
  "single",
  "sound",
  "again",
  "community",
  "definition",
  "focus",
  "individual",
  "matter",
  "safety",
  "turn",
  "everything",
  "kind",
  "quality",
  "soil",
  "ask",
  "board",
  "buy",
  "guard",
  "hold",
  "language",
  "later",
  "return",
  "run",
  "study",
  "teach",
  "oil",
  "situation",
  "easy",
  "cost",
  "decision",
  "purple",
  "responsible",
  "save",
  "staff",
  "stop",
  "teach",
  "character",
  "face",
  "lot",
  "my",
  "option",
  "role",
  "through",
  "important",
  "understand",
  "while",
  "writing",
  "necessary",
  "pattern",
  "prove",
  "rather",
  "teacher",
  "college",
  "cut",
  "especially",
  "hard",
  "leave",
  "might",
  "student",
  "across",
  "alone",
  "beyond",
  "during",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  ",",
  ":",
  ";",
  ".",
  "!",
  "(",
  ")",
  "[",
  "]",
  "{",
  "}",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "+",
  "=",
  "-",
  
]

// Nepali common words
const nepaliWords = [
  "म",
  "हामी",
  "तिमी",
  "तपाईं",
  "उ",
  "उनी",
  "यो",
  "त्यो",
  "कोही",
  "केही",
  "गर्नु",
  "हुनु",
  "जानु",
  "आउनु",
  "खानु",
  "पिउनु",
  "सुत्नु",
  "उठ्नु",
  "बस्नु",
  "दौड्नु",
  "हाँस्नु",
  "रुनु",
  "लेख्नु",
  "पढ्नु",
  "बोल्नु",
  "सुन्नु",
  "देख्नु",
  "धुनु",
  "किन्नु",
  "बेच्नु",
  "मानिस",
  "केटा",
  "केटी",
  "बुबा",
  "आमा",
  "दाजु",
  "भाइ",
  "दिदी",
  "बहिनी",
  "साथी",
  "शिक्षक",
  "डाक्टर",
  "घर",
  "कोठा",
  "ढोका",
  "झ्याल",
  "बाटो",
  "सडक",
  "नदी",
  "पहाड",
  "सूर्य",
  "चन्द्रमा",
  "तारा",
  "आकाश",
  "बादल",
  "पानी",
  "आगो",
  "हावा",
  "माटो",
  "बगैंचा",
  "कुकुर",
  "बिरालो",
  "हात्ती",
  "घोडा",
  "गाई",
  "भैंसी",
  "स्याल",
  "बाघ",
  "सिंह",
  "माछा",
  "भात",
  "दाल",
  "तरकारी",
  "मासु",
  "माछा",
  "दूध",
  "दही",
  "चिनी",
  "नुन",
  "तेल",
  "स्याउ",
  "केरा",
  "अङ्गुर",
  "नास्पाती",
  "लिची",
  "आँप",
  "कागती",
  "गोलभेडा",
  "मकै",
  "चामल",
  "रंगहरू",
  "रातो",
  "हरियो",
  "निलो",
  "पहेँलो",
  "सेतो",
  "कालो",
  "खैरो",
  "गुलाबी",
  "बैंगनी",
  "सुन्तला",
  "बिहान",
  "दिउँसो",
  "साँझ",
  "रात",
  "आज",
  "हिजो",
  "भोलि",
  "हप्ता",
  "महिना",
  "वर्ष",
  "खुसी",
  "दुःख",
  "रिस",
  "डर",
  "माया",
  "घृणा",
  "आशा",
  "निराशा",
  "चिन्ता",
  "उत्साह",
  "एक",
  "दुई",
  "तीन",
  "चार",
  "पाँच",
  "छ",
  "सात",
  "आठ",
  "नौ",
  "दश",
  "टाउको",
  "आँखा",
  "नाक",
  "मुख",
  "कान",
  "हात",
  "खुट्टा",
  "पेट",
  "मुटु",
  "घाँटी",
  "सर्ट",
  "प्यान्ट",
  "साडी",
  "चोलो",
  "टोपी",
  "जुत्ता",
  "मोजा",
  "गहना",
  "चुरा",
  "माला",
  "खाट",
  "तकिया",
  "रजाई",
  "चिमनी",
  "बर्तन",
  "काँच",
  "प्लेट",
  "गिलास",
  "चम्चा",
  "छुरी",
  "गर्मी",
  "जाडो",
  "वर्षा",
  "बसन्त",
  "हिउँद",
  "आँधी",
  "बतास",
  "धुवाँ",
  "झरी",
  "तुषार",
  "किताब",
  "कापी",
  "कलम",
  "पेन्सिल",
  "रबर",
  "पाठ",
  "विद्यालय",
  "क्याम्पस",
  "परीक्षा",
  "अङ्क",
  "साइकल",
  "मोटरसाइकल",
  "कार",
  "बस",
  "ट्रक",
  "जहाज",
  "हेलिकप्टर",
  "ट्रेन",
  "रिक्सा",
  "ट्याक्सी",
  "मन्दिर",
  "मस्जिद",
  "गुम्बा",
  "चर्च",
  "पूजा",
  "प्रार्थना",
  "धर्म",
  "संस्कृति",
  "परम्परा",
  "चाड",
  "रोग",
  "स्वास्थ्य",
  "औषधि",
  "हस्पिटल",
  "नर्स",
  "चिकित्सक",
  "दुखाइ",
  "ज्वरो",
  "खोकी",
  "रक्तचाप",
  "फुटबल",
  "क्रिकेट",
  "भलिबल",
  "बास्केटबल",
  "ब्याडमिन्टन",
  "हाकी",
  "दौड",
  "तैराकी",
  "मुक्केबाजी",
  "जिम",
  "किसान",
  "मजदुर",
  "व्यापारी",
  "शिक्षक",
  "इन्जिनियर",
  "डाक्टर",
  "वकिल",
  "चालक",
  "नर्स",
  "लेखक",
  "कम्प्युटर",
  "मोबाइल",
  "टेलिभिजन",
  "रेडियो",
  "इन्टरनेट",
  "क्यामेरा",
  "माइक",
  "स्पिकर",
  "प्रिन्टर",
  "स्क्यानर",
  "पूर्व",
  "पश्चिम",
  "उत्तर",
  "दक्षिण",
  "दायाँ",
  "बायाँ",
  "अगाडि",
  "पछाडि",
  "माथि",
  "तल",
  "राम्रो",
  "नराम्रो",
  "सानो",
  "ठूलो",
  "लामो",
  "छोटो",
  "गह्रौं",
  "हलुका",
  "पुरानो",
  "नयाँ",
  "धेरै",
  "अलि",
  "चाँडो",
  "बिस्तारै",
  "यहाँ",
  "त्यहाँ",
  "अहिले",
  "पछि",
  "सधैं",
  "कहिल्यै",
  "मा",
  "को",
  "लाई",
  "बाट",
  "देखि",
  "सम्म",
  "सँग",
  "बिना",
  "विपरीत",
  "नजिक",
  "र",
  "तर",
  "कि",
  "यदि",
  "किनभने",
  "जब",
  "जस्तो",
  "अर्थात्",
  "वा",
  "अझ",
  "आहा",
  "ओहो",
  "हाइट",
  "धन्यवाद",
  "माफ गर्नुहोस्",
  "नमस्ते",
  "अलविदा",
  "शुभप्रभात",
  "शुभरात्री",
  "स्वागतम्",
  "सजिलो",
  "गाह्रो",
  "सफा",
  "फोहोर",
  "गीला",
  "सुख्खा",
  "उज्यालो",
  "अँध्यारो",
  "मीठो",
  "पिरो",
  "कुरा",
  "विषय",
  "समस्या",
  "समाधान",
  "योजना",
  "अवसर",
  "चुनौती",
  "अनुभव",
  "ज्ञान",
  "सपना",
  "के",
  "किन",
  "कसरी",
  "कहाँ",
  "कहिले",
  "कति",
  "को",
  "कसले",
  "कुन",
  "कस्तो",
  "समाज",
  "परिवार",
  "मित्र",
  "शत्रु",
  "पडोसी",
  "सहयोग",
  "विवाद",
  "शान्ति",
  "युद्ध",
  "एकता",
  "पैसा",
  "बैंक",
  "बचत",
  "खर्च",
  "आय",
  "व्यय",
  "लाभ",
  "नोक्सान",
  "व्यापार",
  "उद्योग",
  "राजनीति",
  "सरकार",
  "नेता",
  "मन्त्री",
  "प्रधानमन्त्री",
  "राष्ट्रपति",
  "चुनाव",
  "पार्टी",
  "कानून",
  "अधिकार",
  "अदालत",
  "जज",
  "वकिल",
  "गुनाह",
  "सजाय",
  "न्याय",
  "कैद",
  "जरिवाना",
  "साक्षी",
  "प्रमाण",
  "विज्ञान",
  "प्रविधि",
  "अनुसन्धान",
  "प्रयोग",
  "तथ्य",
  "सिद्धान्त",
  "खगोल",
  "रसायन",
  "भौतिक",
  "जीव",
  "जोड",
  "घटाउ",
  "गुणन",
  "भाग",
  "बराबर",
  "अंक",
  "ज्यामिति",
  "बीजगणित",
  "त्रिकोण",
  "वर्ग",
  "भाषा",
  "व्याकरण",
  "शब्द",
  "वाक्य",
  "अर्थ",
  "उच्चारण",
  "लिपि",
  "अनुवाद",
  "मातृभाषा",
  "विदेशी",
  "कला",
  "संगीत",
  "नृत्य",
  "चित्र",
  "मूर्ति",
  "साहित्य",
  "कविता",
  "कथा",
  "नाटक",
  "फिल्म",
  "ईश्वर",
  "भगवान",
  "पूजा",
  "मन्त्र",
  "प्रार्थना",
  "तीर्थ",
  "यज्ञ",
  "व्रत",
  "ध्यान",
  "मोक्ष",
  "इतिहास",
  "युद्ध",
  "शान्ति",
  "सन्धि",
  "साम्राज्य",
  "राजा",
  "रानी",
  "क्रान्ति",
  "स्वतन्त्रता",
  "दासता",
  "भूगोल",
  "महादेश",
  "देश",
  "नगर",
  "गाउँ",
  "हिमाल",
  "तराई",
  "पहाड",
  "मैदान",
  "समुद्र",
  "तापक्रम",
  "आर्द्रता",
  "वर्षा",
  "हिउँ",
  "बादल",
  "आँधी",
  "तूफान",
  "सुख्खा",
  "बाढी",
  "भूकम्प",
  "सूर्य",
  "चन्द्रमा",
  "तारा",
  "ग्रह",
  "आकाशगङ्गा",
  "उल्का",
  "ग्रहण",
  "नक्षत्र",
  "ब्रह्माण्ड",
  "अन्तरिक्ष",
  "पर्यावरण",
  "प्रदूषण",
  "हरियाली",
  "जंगल",
  "वन्यजन्तु",
  "संरक्षण",
  "पुनर्चक्रण",
  "सौर्य ऊर्जा",
  "जलवायु परिवर्तन",
  "जैविक",
  "मन",
  "भावना",
  "विचार",
  "तनाव",
  "मानसिक",
  "आत्मविश्वास",
  "डर",
  "खुशी",
  "दुःख",
  "प्रेरणा",
  "दर्शन",
  "जीवन",
  "मृत्यु",
  "सत्य",
  "असत्य",
  "न्याय",
  "अन्याय",
  "नैतिकता",
  "अस्तित्व",
  "चेतना",
  "साहस",
  "जोखिम",
  "यात्रा",
  "अन्वेषण",
  "रहस्य",
  "उपलब्धि",
  "चुनौती",
  "विजय",
  "पराजय",
  "सफलता",
  ",",
  "।",
  "१",
  "२",
  "३",
  "४",
  "५",
  "६",
  "७",
  "८",
  "९",
  "०",
  "अ",
  "आ",
  "इ",
  "ई",
  "उ",
  "ऊ",
  "ए",
  "ऐ",
  "ओ",
  "औ",
  "क",
  "ख",
  "ग",
  "घ",
  "ङ",
  "च",
  "छ",
  "ज",
  "झ",
  "ञ",
  "ट",
  "ठ",
  "ड",
  "ढ",
  "ण",
  "त",
  "थ",
  "द",
  "ध",
  "न",
  "प",
  "फ",
  "ब",
  "भ",
  "म",
  "य",
  "र",
  "ल",
  "व",
  "श",
  "ष",
  "स",
  "ह",
  "क्ष",
  "त्र",
  "ज्ञ",
]

// Nepali quotes
const nepaliQuotes = [
  "सपना देख्नेहरू नै परिवर्तन ल्याउने गर्दछन्।",
  "समयको मूल्य बुझ्नेलाई जीवन सजिलो हुन्छ।",
  "असफलता सफलता तर्फको पहिलो पाइला हो।",
  "जीवनमा संघर्ष नगरी केही प्राप्त हुँदैन।",
  "सच्चा मित्र सधैं दुःखमा चिनिन्छ।",
  "इमानदार व्यक्तिको यात्रा ढिलो भए पनि टाढासम्म पुग्छ।",
  "सकारात्मक सोचले असम्भवलाई सम्भव बनाउँछ।",
  "प्रेम तब बलियो हुन्छ जब विश्वास गहिरो हुन्छ।",
  "कठिनाइहरू नै अवसर ल्याउने ढोका हुन्।",
  "शिक्षा केवल किताबको पाना होइन, व्यवहारको पाठ पनि हो।",
  "सपना पुरा गर्न संघर्ष आवश्यक छ।",
  "समयको मूल्य बुझ्नाले जीवनलाई अर्थपूर्ण बनाउँछ।",
  "असफलता सफलता प्राप्तिको पहिलो कदम हो।",
  "जीवनमा संघर्ष नगरी सफलता प्राप्त गर्न सकिँदैन।",
  "सच्चा मित्र सधैं दुःखको समयमा साथ दिन्छ।",
  "इमानदार व्यक्तिको यात्रा ढिलो भए पनि टाढासम्म पुग्छ।",
  "सकारात्मक सोचले असम्भवलाई सम्भव बनाउँछ।",
  "प्रेम तब बलियो हुन्छ जब विश्वास गहिरो हुन्छ।",
  "कठिनाइहरू नै अवसर ल्याउने ढोका हुन्।",
  "शिक्षा केवल किताबको पाना होइन, व्यवहारको पाठ पनि हो।",
  "शिक्षा भनेको केवल किताबको अध्ययन होइन, जीवनका अनुभवबाट पनि सिक्नु हो।",
  "ज्ञान प्राप्ति निरन्तर प्रक्रिया हो, जसले जीवनलाई उज्यालो बनाउँछ।",
  "शिक्षाले मानिसलाई सोच्न र निर्णय गर्न सक्षम बनाउँछ।",
  "अधिकार र कर्तव्यसँगै शिक्षा पनि जिम्मेवारी हो।",
  "शिक्षा समाजको दर्पण हो, जसले समाजको स्तर निर्धारण गर्छ।",
  "शिक्षा बिना मानिसको जीवन अधुरो हुन्छ।",
  "ज्ञानको खोजी जीवनभरि जारी राख्नु पर्छ।",
  "शिक्षाले मानिसलाई सभ्य र संस्कारी बनाउँछ।",
  "शिक्षा समाजको उत्थानको आधार हो।",
  "ज्ञानको प्रकाशले अन्धकारलाई हटाउँछ।",
  "साँचो मित्र सधैं साथ दिन्छ, चाहे परिस्थिति जस्तोसुकै होस्।",
  "मित्रता विश्वास र समझदारीमा आधारित हुन्छ।",
  "साँचो मित्रले तपाईंको कमजोरीलाई स्वीकार्छ र सुधार्न मद्दत गर्छ।",
  "मित्रता जीवनको अनमोल रत्न हो।",
  "साँचो मित्र सँगै हाँस्न र रुन सकिन्छ।",
  "मित्रता समय र दूरीको बाँधमा बाँधिँदैन।",
  "साँचो मित्रले तपाईंको खुशीमा खुशी र दुःखमा दुःख सँगै भोग्छ।",
  "मित्रता भनेको एक अर्काको साथ र समर्थन हो।",
  "साँचो मित्रले तपाईंको असफलतामा पनि साथ दिन्छ।",
  "मित्रता जीवनको यात्रा सजिलो बनाउँछ।",
  "सकारात्मक सोचले जीवनलाई उज्यालो बनाउँछ।",
  "आत्मविश्वासले कठिनाइलाई अवसरमा परिवर्तन गर्छ।",
  "सकारात्मक सोचले असम्भवलाई सम्भव बनाउँछ।",
  "आत्मविश्वासले मानिसलाई आफ्नो लक्ष्यमा केन्द्रित राख्छ।",
  "सकारात्मक सोचले मानिसलाई उत्साही र प्रेरित बनाउँछ।",
  "आत्मविश्वासले मानिसलाई आफ्नो क्षमता पहिचान गर्न मद्दत गर्छ।",
  "सकारात्मक सोचले मानसिक शान्ति र सन्तुष्टि ल्याउँछ।",
  "आत्मविश्वासले मानिसलाई आफ्नो निर्णयमा दृढ बनाउँछ।",
  "सकारात्मक सोचले मानिसलाई जीवनका चुनौतीलाई सामना गर्न सक्षम बनाउँछ।",
  "आत्मविश्वासले मानिसलाई आफ्नो लक्ष्य प्राप्तिमा सफल बनाउँछ।",
  "सपना पुरा गर्न धैर्यता अनिवार्य छ।",
  "परिश्रम बिना सफलता असम्भव छ।",
  "प्रयास नछोड्नेले मात्र सफलता पाउँछन्।",
  "सफलता त्यही हो जसले असफलताबाट सिक्छ।",
  "हार मान्नु भन्दा प्रयास गर्न छोड्नु बढी ठुलो गल्ती हो।",
  "आफ्नो लक्ष्यमा अडिग रहनु नै जीत हो।",
  "सपना देख्नुस्, तर त्यसका लागि काम पनि गर्नुस्।",
  "कठिनाइमा हार नमान्नुस्, त्यो तपाईंलाई बलियो बनाउँछ।",
  "सपना पुरा गर्नका लागि पहिलो कदम चाल्नु जरुरी छ।",
  "सफलता कहिले पनि सजिलो बाटोमा आउँदैन।",
  "असफलता भयभीत हुनुपर्ने कारण होइन, अभ्यास गर्नुपर्ने मौका हो।",
  "सपना देख्न भन्दा तिनीहरूलाई पुरा गर्न मेहनत गर्नु महत्त्वपूर्ण छ।",
  "आफ्नो कमजोरीलाई कमजोरी मान्नु भन्दा सुधार्ने सोच राख्नुस्।",
  "परिस्थितिले होइन, तपाईंको सोचले तपाईंको जीवन निर्धारण गर्छ।",
  "सपना देख्नुहोस्, योजना बनाउनुहोस् र त्यसमा अमल गर्नुहोस्।",
  "कठिन समयले नै मानिसको चरित्र बनाउँछ।",
  "जीवनमा कुनै छोटो बाटो हुँदैन, मात्र निरन्तर प्रयास गर्छौं।",
  "सपना पुरा गर्न साहस र मेहनत दुवै चाहिन्छ।",
  "निराशा र असफलताले मात्र सफलताको मूल्य देखाउँछ।",
  "सफलता आफ्नो मेहनतको प्रतिफल हो।",
  "तपाईंको हरेक असफलता एउटा नयाँ सिकाइ हो।",
  "सपना देख्नु र त्यसको पछाडि लाग्नु नै जीवनको सार हो।",
  "धैर्य र परिश्रमले नै कठिनाईलाई जित्न सकिन्छ।",
  "परिस्थितिले कसैलाई पनि रोक्न सक्दैन, जबसम्म आफैं रोकिँदैन।",
  "सपना पुरा गर्नको लागि कुनै पनि बाधा अपरिहार्य छैन।",
  "आफ्नो क्षमता पहिचान गरेर त्यसमा विश्वास गर्नुस्।",
  "हिम्मत नहार्नुस्, सफलता एक दिन तपाईंको पर्खाइमा छ।",
  "तपाईंको सोच र प्रयासले तपाईंको भाग्य बनाउँछ।",
  "सपना पुरा गर्न निरन्तर प्रयास आवश्यक छ।",
  "परिश्रम नै सफलता प्राप्तिको गुरुकिल्ली हो।",
  "जीवनमा संघर्षले नै विजय ल्याउँछ।",
  "सपना पुरा गर्न कहिले पनि ढिलाइ नगर्नुस्।",
  "आफ्नो लक्ष्यप्रति समर्पित रहनुस्।",
  "सफलता हासिल गर्न सबैभन्दा पहिले विश्वास गर्नुपर्छ।",
  "परिश्रम गर्नेले कहिले असफल हुँदैन।",
  "जीवनको असली जीत संघर्षमा हुन्छ।",
  "सपना देख्नेले मात्र सफलताको स्वाद चाख्न सक्छ।",
  "परिश्रम नगरी सफलता पाउन सकिँदैन।",
  "सपना पुरा गर्नका लागि योजना र कार्यान्वयन दुवै जरूरी छन्।",
  "सपना पुरा गर्नेहरूको मनमा कहिल्यै हार हुँदैन।",
  "सफलता त केवल सपना देख्नेलाई मात्र होइन, त्यसका लागि काम गर्नेहरूलाई पनि प्राप्त हुन्छ।",
  "संघर्षले नै मानिसलाई बलियो बनाउँछ।",
  "सपना देख्नुस्, तर त्यहाँ अडिन पनि जानुस्।",
  "आशा नछोड्नुस्, सफलता एक दिन अवश्य भेटिन्छ।",
  "जीवनको मूल्य संघर्षमा मात्र पहिचानिन्छ।",
  "सपना पुरा गर्न निरन्तर प्रयास गर्नु नै सफलता हो।",
  "आत्मविश्वास र मेहनतले कुनै पनि बाधा पार गर्न सकिन्छ।",
  "सपना पुरा गर्न सबैभन्दा पहिले आफूलाई विश्वास गर्नुपर्छ।",
  "संघर्ष बिना जीवन अधूरो हुन्छ।",
  "सपना देख्नेले मात्र इतिहास रच्न सक्छ।",
  "शिक्षा त केवल ज्ञान होइन, चरित्र निर्माण पनि हो।",
  "ज्ञान बाँड्दा बढ्छ, शिक्षा बाँड्दा समाज समृद्ध हुन्छ।",
  "पढाइले मात्र होइन, सिकाइले पनि जीवन चम्किन्छ।",
  "शिक्षाले मानिसलाई उज्यालो र मार्गदर्शन दिन्छ।",
  "ज्ञान प्राप्त गर्न कहिल्यै ढिलाइ हुँदैन।",
  "प्रेम बिना जीवन अधुरो हुन्छ।",
  "साँचो प्रेम कहिल्यै स्वार्थी हुँदैन।",
  "विश्वासको आधारमा प्रेम बलियो हुन्छ।",
  "प्रेमले मानिसलाई सहिष्णु र दयालु बनाउँछ।",
  "प्रेमले मनलाई शान्ति र खुशी दिन्छ।",
  "जीवन छोटो छ, त्यसलाई प्रेम र माया गरेर सजाऔं।",
  "सच्चा प्रेमले सबै बाधा पार गर्छ।",
  "शिक्षाले आत्मबल बढाउँछ।",
  "सपना देख्नको लागि ज्ञान जरुरी छ।",
  "जीवनको साँच्चिकै मूल्य प्रेम र मित्रतामा हुन्छ।",
  "सपना देख्नेहरूलाई शिक्षाले मार्ग देखाउँछ।",
  "शिक्षा बिना जीवनमा उज्यालो हुँदैन।",
  "प्रेमले सबैभन्दा ठूलो शक्ति हो।",
  "सपना पुरा गर्न शिक्षा र प्रेम दुवै आवश्यक छन्।",
  "जीवनको सफलता प्रेम र ज्ञानको सही मिश्रणमा हुन्छ।",
  "शिक्षा त केवल बुद्धिमानी होइन, नैतिकता पनि हो।",
  "सपना देख्दा सिक्ने बानी राख्नुपर्छ।",
  "प्रेमले संसारलाई सुन्दर बनाउँछ।",
  "सपना देखेर मात्र होइन, त्यसमा विश्वास गरेर काम गरेर मात्र सफल हुन्छ।",
  "शिक्षा भनेको जीवनलाई बुझ्ने कला हो।",
  "प्रेमले सबैभन्दा गहिरो चिन्ता मेट्छ।",
  "सपना पुरा गर्न आत्मबल र प्रेम दुवै चाहिन्छ।",
  "जीवनमा प्रेम र मित्रता नै सबैभन्दा ठूलो पूँजी हो।",
  "शिक्षाले मानिसको सोचलाई विस्तार गर्छ।",
  "प्रेम बिना जीवनमा कुनै पनि खुशी अधूरो हुन्छ।",
  "शिक्षा जीवनको साँचो दीप हो।",
  "प्रेमले मानिसलाई आफ्नो स्वार्थभन्दा माथि उठ्न सिकाउँछ।",
  "सपना पुरा गर्नका लागि ज्ञान र अनुभव दुवै महत्वपूर्ण छन्।",
  "प्रेमले सबैभन्दा गहिरो चोटहरू पनि निको पार्छ।",
  "शिक्षाले जीवनलाई सफल र सार्थक बनाउँछ।",
  "सपना देख्नलाई मात्र होइन, त्यहाँ पुग्न पनि साहस चाहिन्छ।",
  "प्रेमले संसारलाई राम्रो बनाउँछ।",
  "शिक्षाले मानिसलाई सोच्न र बुझ्न सक्षम बनाउँछ।",
  "सपना पुरा गर्न दृढ इच्छा र प्रेम आवश्यक छ।",
  "जीवनमा प्रेम नै सबैभन्दा ठूलो शिक्षक हो।",
  "शिक्षाले मानिसलाई सत्य र न्यायको बाटो देखाउँछ।",
  "प्रेमले सबैभन्दा कठिन मनलाई पनि सजिलो बनाउँछ।",
  "सपना पुरा गर्न आफूमा विश्वास हुनु जरूरी छ।",
  "शिक्षा र प्रेम दुवैले जीवनको मार्गदर्शन गर्छ।",
  "सपना देख्न डर नमान्नुस्, त्यसका लागि कर्म गर्नुस्।",
  "प्रेमले जीवनलाई अर्थपूर्ण बनाउँछ।",
  "शिक्षा बिना जीवनमा अन्धकार हुन्छ।",
  "प्रेमले मानिसलाई समृद्ध र खुशहाल बनाउँछ।",
  "सपना पुरा गर्न परिश्रम र प्रेम दुवै जरूरी छन्।",
  "जीवनमा प्रेम र शिक्षा दुवैको मूल्य सर्वोपरि छ।",
  "सफलता त्यही हो जसले असफलताबाट सिक्न सक्छ।",
  "संघर्ष बिना कुनै ठूलो उपलब्धि सम्भव छैन।",
  "आफ्नो कमजोरीलाई स्वीकार गर्न सक्नेले मात्र अगाडि बढ्छ।",
  "धैर्य र परिश्रमले मात्र सफलताको ढोका खोल्छ।",
  "हार मान्नु भन्दा नयाँ बाटो खोज्नुस्।",
  "सपना देख्नुस्, तर त्यसका लागि योजना बनाउनु आवश्यक छ।",
  "संघर्षले नै मानिसलाई बलियो र सक्षम बनाउँछ।",
  "सफलता मात्र लक्ष्य होइन, त्यो यात्रा पनि हो।",
  "प्रयास नछोड्नेले मात्र अन्ततः विजय प्राप्त गर्छ।",
  "आत्मविश्वास नै सफलताको कुञ्जी हो।",
  "सपना देख्न साहस चाहिन्छ, पुरा गर्न मेहनत।",
  "परिश्रम बिना सफलता केवल कल्पना हो।",
  "संघर्षले नतिजा दिन्छ, आशा भनेको ऊर्जा हो।",
  "असफलताले तपाईंलाई सिकाउँछ कि कसरि अगाडि बढ्ने।",
  "सफलता त्यही हो जसले असफलतालाई चुनौती दिन्छ।",
  "तपाईंको मेहनतले मात्र भविष्य निर्माण हुन्छ।",
  "धैर्यता राख्नुस्, सफलताको मार्ग लामो हुन्छ।",
  "सपना पुरा गर्न निरन्तर प्रयास जरुरी छ।",
  "सफलता अन्तिम गन्तव्य होइन, निरन्तर यात्रा हो।",
  "संघर्षले जीवनलाई अर्थपूर्ण बनाउँछ।",
  "सपना देख्न सजिलो छ, त्यसलाई पुरा गर्न चुनौती।",
  "संघर्ष नै सफलता प्राप्तिको सूत्र हो।",
  "आफ्नो कमजोरीलाई सुधार्नु नै विकास हो।",
  "सफलता धैर्य र विश्वासको परिणाम हो।",
  "हार मान्नु भनेको प्रयासलाई त्याग्नु हो।",
  "सपना पुरा गर्न तपाईको मेहनत नै निर्णायक हुन्छ।",
  "संघर्षले मात्र महानता जन्माउँछ।",
  "सफलता त केवल काम गर्नेहरूको हुन्छ।",
  "प्रयासलाई कहिले पनि कम आँकलन नगर्नुस्।",
  "आत्मविश्वास र धैर्यले संसार जित्न सकिन्छ।",
  "सपना देखेर मात्रै सफल हुँदैन, मेहनत गर्नुपर्छ।",
  "संघर्षले तपाईंलाई नयाँ अवसरहरू दिन्छ।",
  "हार नमान्नु सफलताको पहिलो कदम हो।",
  "सपना पुरा गर्न इच्छाशक्ति बलियो हुनुपर्छ।",
  "धैर्य राख्नुस्, सफलता एक दिन अवश्य आउनेछ।",
  "सफलता तपाईको सोच र प्रयासमा निर्भर गर्दछ।",
  "संघर्षले तपाईलाई अझ बलियो बनाउँछ।",
  "सपना पुरा गर्न निरन्तरता अनिवार्य छ।",
  "आफ्नो लक्ष्यलाई कहिल्यै नछोड्नुस्।",
  "सफलता धैर्य, मेहनत र विश्वासको फल हो।",
  "सपना पुरा गर्न आत्मबल र सकारात्मक सोच जरूरी छ।",
  "संघर्षले तपाईंको मनोबल बढाउँछ।",
  "हार मान्नेहरू कहिले पनि सफल हुँदैनन्।",
  "सपना पुरा गर्न काममा लगन आवश्यक छ।",
  "सफलता तपाईको दृढ संकल्पमा निर्भर हुन्छ।",
  "संघर्ष नै तपाईलाई जीवनमा सफलता दिन्छ।",
  "सपना देख्न र त्यसमा विश्वास गर्न कहिल्यै नछोड्नुस्।",
  "धैर्य र मेहनतले सफलताको ढोका खोल्छ।",
  "सफलता एउटा प्रक्रिया हो, गन्तव्य होइन।",
  "संघर्ष र सफलताले मात्र जीवनलाई अर्थ दिन्छ।",
  "जीवनमा हार नमान्नेहरू मात्र सफल हुन्छन्।",
  "आत्मविश्वासले मनमा डर हटाउँछ।",
  "सपना पुरा गर्न जुनून अनिवार्य छ।",
  "सफलताको लागि निरन्तर प्रयास गर्नुपर्छ।",
  "संघर्षले नै मानिसलाई जित्न सिकाउँछ।",
  "धैर्यले मात्र कठिनाइ पार गर्न सकिन्छ।",
  "सपना देख्नुस् र त्यसमा विश्वास गर्नुस्।",
  "प्रयासलाई कहिल्यै कम आँकलन नगर्नुस्।",
  "आत्मविश्वासले सफलता सुनिश्चित गर्छ।",
  "जीवनमा सकारात्मक सोच राख्नुस्।",
  "सपना पुरा गर्न परिश्रम गर्नु पर्छ।",
  "हार नमान्नेलाई सफलता अवश्य भेटिन्छ।",
  "संघर्ष नै जीवनको गुरु हो।",
  "आत्मबल बढाउनुहोस्, जीवन सहज हुन्छ।",
  "सफलता आफ्नो मेहनतको फल हो।",
  "सपना देख्नेहरू कहिल्यै नडराउन।",
  "धैर्य राख्नुस्, सफलता तपाईंकै हो।",
  "सकारात्मक सोचले जीवन बदलेको हुन्छ।",
  "सपना पुरा गर्न विश्वास जरुरी छ।",
  "संघर्षले नै जीवनमा उज्यालो ल्याउँछ।",
  "जीवनको सबैभन्दा ठूलो पूँजी आत्मविश्वास हो।",
  "सफलताको लागि कहिल्यै ढिलाइ नगर्नुस्।",
  "सपना पुरा गर्न आत्मबल आवश्यक छ।",
  "परिश्रम नगरी सफलता सम्भव छैन।",
  "संघर्षले नै मानिसको चरित्र बनाउँछ।",
  "आत्मविश्वासले जीवन सजिलो बनाउँछ।",
  "सपना देख्नु मात्र होइन, तिनीहरूलाई पुरा गर्नुस्।",
  "धैर्य र परिश्रमले जीवन उज्यालो बनाउँछ।",
  "सकारात्मक सोच राख्नुस् र अघि बढ्नुस्।",
  "सपना पुरा गर्न कहिल्यै नडराउनुस्।",
  "संघर्षको सामना गर्नेले मात्र सफलताको स्वाद चाख्छ।",
  "आत्मविश्वासले जीवनलाई सशक्त बनाउँछ।",
  "सपना पुरा गर्न दृढ इच्छा राख्नुपर्छ।",
  "धैर्य र मेहनतले मात्र सपना पुरा हुन्छ।",
  "सकारात्मक सोचले असम्भवलाई सम्भव बनाउँछ।",
  "सपना पुरा गर्न आफूमाथि विश्वास गर्नुपर्छ।",
  "संघर्ष नै जीवनको वास्तविक शिक्षक हो।",
  "सफलता मेहनत र आत्मविश्वासको परिणाम हो।",
  "जीवनमा कहिल्यै हार नमान्नुस्।",
  "सपना देख्नु र त्यसमा लाग्नु जीवनको सार हो।",
  "संघर्षले मानिसलाई दृढ र सक्षम बनाउँछ।",
  "आत्मविश्वासले जीवनको मार्ग उज्यालो बनाउँछ।",
  "सपना पुरा गर्न कहिल्यै नछुट्नुहोस्।",
  "धैर्य राख्नुस्, सफलता एक दिन अवश्य आउनेछ।",
  "सकारात्मक सोचले जीवनमा नयाँ अवसर ल्याउँछ।",
  "सपना देख्न र तिनलाई पुरा गर्न साहस राख्नुस्।",
  "संघर्षले नै मानिसको अस्तित्व तय गर्छ।",
  "आत्मविश्वासले जीवनको सबै बाधा पार गर्न सकिन्छ।",
  "सफलता मेहनत र दृढ संकल्पको नतिजा हो।",
  "सपना पुरा गर्न कहिल्यै हार नमान्नुस्।",
  "आफ्नो क्षमतामा विश्वास राख्नुहोस्, सफलता नजिकै छ।",
  "धैर्य राख्नुस्, सबै कुरा समयमै हुन्छ।",
  "सपना पुरा गर्न निरन्तर प्रयास गरिरहनुपर्छ।",
  "हार मान्नु भनेको अर्को मौका गुमाउनु हो।",
  "सफलता त्यहीलाई प्राप्त हुन्छ जसले कहिल्यै हार मान्दैन।",
  "आत्मबलले मानिसलाई अगाडि बढाउँछ।",
  "संघर्षले मानिसको जीवनलाई परिपक्व बनाउँछ।",
  "सपना देख्नुस् र त्यसका लागि कर्म गर्नुस्।",
  "धैर्य र परिश्रमले सफलता ल्याउँछ।",
  "सकारात्मक सोचले असम्भवलाई सम्भव बनाउँछ।",
  "आत्मविश्वास राख्नुस्, जीवन आफै सरल हुन्छ।",
  "सपना पुरा गर्न कहिल्यै हार नमान्नुस्।",
  "संघर्ष नै जीवनको सबैभन्दा ठूलो शिक्षक हो।",
  "परिश्रम बिना सफलता सम्भव छैन।",
  "आत्मबल र धैर्यले जीवन सजिलो हुन्छ।",
  "सपना देख्नेहरूलाई संसार बदल्न सक्ने शक्ति हुन्छ।",
  "धैर्य राख्नुस्, सफलताको मार्ग लामो हुन्छ।",
  "सकारात्मक सोचले जीवनमा खुशी ल्याउँछ।",
  "सपना पुरा गर्न आत्मविश्वास र मेहनत अनिवार्य छ।",
  "संघर्षले तपाईलाई अझ बलियो बनाउँछ।",
  "सफलता निरन्तर प्रयासको परिणाम हो।",
  "आत्मबलले मानिसलाई जीवनको सबै चुनौती पार गर्न सहयोग गर्छ।",
  "सपना देख्नुस्, त्यसका लागि प्रयास गर्नुस्।",
  "धैर्य र मेहनतले सफलता पक्कै मिल्छ।",
  "सकारात्मक सोचले सबै कठिनाइ पार गर्न सकिन्छ।",
  "संघर्षले तपाईलाई नयाँ अवसर दिन्छ।",
  "आत्मविश्वासले जीवनलाई उज्यालो बनाउँछ।",
  "सपना पुरा गर्न कहिल्यै हार नमान्नुस्।",
  "धैर्य राख्नुस्, सफलता एक दिन अवश्य आउनेछ।",
  "सफलता प्रयास गर्नेहरूको मात्र हुन्छ।",
  "आत्मबलले कुनै पनि चुनौती पार गर्न सक्छ।",
  "संघर्ष बिना जीवन अधुरो हुन्छ।",
  "सपना पुरा गर्न निरन्तर प्रयास गरिरहनुपर्छ।",
  "धैर्य र मेहनतले मात्र सफलता सम्भव छ।",
  "सकारात्मक सोचले जीवनलाई उज्यालो बनाउँछ।",
  "सपना देख्नुस् र त्यसका लागि कर्म गर्नुस्।",
  "संघर्षले तपाईलाई बलियो र सक्षम बनाउँछ।",
  "आत्मविश्वास राख्नुस्, सफलता तपाईंकै हो।",
  "सपना पुरा गर्न कहिल्यै नडराउनुस्।",
  "धैर्य राख्नुस्, सफलता एक दिन अवश्य प्राप्त हुन्छ।",
  "सपना देख्नेहरूले मात्र भविष्य बनाउन सक्छन्।",
  "संघर्षले जीवनलाई सार्थक बनाउँछ।",
  "आत्मबलले जीवनको सबै बाधा हटाउँछ।",
  "सपना पुरा गर्न धैर्यता अनिवार्य छ।",
  "धैर्य र मेहनतले जीवन उज्यालो हुन्छ।",
  "सकारात्मक सोचले सबै समस्याको समाधान दिन्छ।",
  "संघर्षले तपाईलाई सफलताको मार्ग देखाउँछ।",
  "आत्मविश्वासले जीवन सजिलो बनाउँछ।",
  "सपना पुरा गर्न कहिल्यै हार नमान्नुस्।",
  "धैर्य राख्नुस्, सफलता एक दिन अवश्य भेटिन्छ।",
]

const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
  "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "Dream big and dare to fail. – Norman Vaughan",
  "Opportunities don’t happen. You create them. – Chris Grosser",
  "Hard work beats talent when talent doesn’t work hard. – Tim Notke",
  "Life is what happens to you while you're busy making other plans. – John Lennon",
  "Life is really simple, but we insist on making it complicated. – Confucius",
  "In the end, it’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
  "The purpose of our lives is to be happy. – Dalai Lama",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "You only live once, but if you do it right, once is enough. – Mae West",
  "Life is either a daring adventure or nothing at all. – Helen Keller",
  "The biggest adventure you can take is to live the life of your dreams. – Oprah Winfrey",
  "Life is short, and it’s up to you to make it sweet. – Sarah Louise Delany",
  "The unexamined life is not worth living. – Socrates",
  "It is during our darkest moments that we must focus to see the light. – Aristotle",
  "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
  "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success. – James Cameron",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Strength does not come from winning. Your struggles develop your strengths. – Arnold Schwarzenegger",
  "The harder the conflict, the greater the triumph. – George Washington",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. – Thomas Edison",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "Perseverance is failing 19 times and succeeding the 20th. – Julie Andrews",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "If you look at what you have in life, you’ll always have more. – Oprah Winfrey",
  "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
  "The happiest people don’t have the best of everything, they make the best of everything. – Anonymous",
  "Happiness is a choice, not a result. – Ralph Marston",
  "Positive thinking will let you do everything better than negative thinking will. – Zig Ziglar",
  "Joy does not simply happen to us. We have to choose joy and keep choosing it every day. – Henri Nouwen",
  "The best way to cheer yourself up is to try to cheer somebody else up. – Mark Twain",
  "Happiness is when what you think, what you say, and what you do are in harmony. – Mahatma Gandhi",
  "Be so happy that when others look at you, they become happy too. – Anonymous",
  "Count your age by friends, not years. Count your life by smiles, not tears. – John Lennon",
  "Where there is love, there is life. – Mahatma Gandhi",
  "Love is not about possession. It’s about appreciation. – Osho",
  "The best thing to hold onto in life is each other. – Audrey Hepburn",
  "A successful marriage requires falling in love many times, always with the same person. – Mignon McLaughlin",
  "Love is composed of a single soul inhabiting two bodies. – Aristotle",
  "To love and be loved is to feel the sun from both sides. – David Viscott",
  "We accept the love we think we deserve. – Stephen Chbosky",
  "Love is friendship that has caught fire. – Ann Landers",
  "The greatest happiness of life is the conviction that we are loved. – Victor Hugo",
  "If you want to be loved, be lovable. – Ovid",
  "Do one thing every day that scares you. – Eleanor Roosevelt",
  "Courage is resistance to fear, mastery of fear—not absence of fear. – Mark Twain",
  "Fear is only as deep as the mind allows. – Japanese Proverb",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "The brave man is not he who does not feel afraid, but he who conquers that fear. – Nelson Mandela",
  "Fear kills more dreams than failure ever will. – Suzy Kassem",
  "You gain strength, courage, and confidence by every experience in which you stop to look fear in the face. – Eleanor Roosevelt",
  "Don’t let fear or insecurity stop you from trying new things. – Anonymous",
  "Fear is a reaction. Courage is a decision. – Winston Churchill",
  "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
  "Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
  "I have not failed. I’ve just found 10,000 ways that won’t work. – Thomas Edison",
  "Failure is the condiment that gives success its flavor. – Truman Capote",
  "Success is stumbling from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "The only real mistake is the one from which we learn nothing. – Henry Ford",
  "Every failure is a step to success. – William Whewell",
  "Mistakes are the portals of discovery. – James Joyce",
  "Failures are finger posts on the road to achievement. – C.S. Lewis",
  "Failure is not the opposite of success; it’s part of success. – Arianna Huffington",
  "You build on failure. You use it as a stepping stone. – Johnny Cash",
  "A leader is one who knows the way, goes the way, and shows the way. – John C. Maxwell",
  "Leadership is not about being in charge. It’s about taking care of those in your charge. – Simon Sinek",
  "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things. – Ronald Reagan",
  "Innovation distinguishes between a leader and a follower. – Steve Jobs",
  "Do not follow where the path may lead. Go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
  "Leadership is the capacity to translate vision into reality. – Warren Bennis",
  "The best way to predict the future is to create it. – Peter Drucker",
  "A good leader takes a little more than his share of the blame, a little less than his share of the credit. – Arnold Glasow",
  "Leadership is not about titles, positions, or flowcharts. It is about one life influencing another. – John C. Maxwell",
  "To handle yourself, use your head; to handle others, use your heart. – Eleanor Roosevelt",
  "Creativity is intelligence having fun. – Albert Einstein",
  "Innovation is seeing what everybody has seen and thinking what nobody has thought. – Albert Szent-Györgyi",
  "The creative adult is the child who survived. – Ursula K. Le Guin",
  "You can’t use up creativity. The more you use, the more you have. – Maya Angelou",
  "Imagination is the beginning of creation. – George Bernard Shaw",
  "Creativity takes courage. – Henri Matisse",
  "The worst enemy to creativity is self-doubt. – Sylvia Plath",
  "Art is not freedom from discipline, but disciplined freedom. – John F. Kennedy",
  "To be creative means to be in love with life. – Osho",
  "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun. – Mary Lou Cook",
  "Time is what we want most, but what we use worst. – William Penn",
  "Don’t count the days, make the days count. – Muhammad Ali",
  "The key is not to prioritize what’s on your schedule, but to schedule your priorities. – Stephen Covey",
  "Lost time is never found again. – Benjamin Franklin",
  "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort. – Paul J. Meyer",
  "You will never find time for anything. If you want time, you must make it. – Charles Buxton",
  "The bad news is time flies. The good news is you’re the pilot. – Michael Altshuler",
  "The shorter way to do many things is to only do one thing at a time. – Mozart",
  "Time management is life management. – Robin Sharma",
  "Do the difficult things while they are easy and do the great things while they are small. – Lao Tzu",

]

const codeSnippets = [
  `function fibonacci(n) {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}`,
  `const quickSort = (arr) => {
  if (arr.length <= 1) return arr;
  const pivot = arr[arr.length - 1];
  const left = arr.filter(x => x < pivot);
  const right = arr.filter(x => x > pivot);
  return [...quickSort(left), pivot, ...quickSort(right)];
};`,
  `class BinaryTree {
  constructor(value) {
    this.value = value;
    this.left = null;
    this.right = null;
  }
  
  insert(value) {
    if (value < this.value) {
      if (!this.left) this.left = new BinaryTree(value);
      else this.left.insert(value);
    } else {
      if (!this.right) this.right = new BinaryTree(value);
      else this.right.insert(value);
    }
  }
}`,
  `const debounce = (func, delay) => {
  let timeoutId;
  return (...args) => {
    clearTimeout(timeoutId);
    timeoutId = setTimeout(() => func.apply(this, args), delay);
  };
};`,
  `async function fetchData(url) {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Fetch error:', error);
    throw error;
  }
}`,
]

export function generateWords(count: number): string {
  const words = []
  for (let i = 0; i < count; i++) {
    words.push(commonWords[Math.floor(Math.random() * commonWords.length)])
  }
  return words.join(" ")
}

export function generateNepaliWords(count: number): string {
  // Ensure count is reasonable
  count = Math.max(1, Math.min(count, 100));
  const words = [];
  for (let i = 0; i < count; i++) {
    words.push(nepaliWords[Math.floor(Math.random() * nepaliWords.length)]);
  }
  return words.join(" ");
}
export async function generateQuote(): Promise<string> {
  return quotes[Math.floor(Math.random() * quotes.length)]
}

export async function generateNepaliQuote(): Promise<string> {
  return nepaliQuotes[Math.floor(Math.random() * nepaliQuotes.length)]
}

export function generateCode(): string {
  return codeSnippets[Math.floor(Math.random() * codeSnippets.length)]
}
